photos/urls.py
from django.urls import path, re_path

from photos import views

app_name = 'photos'
urlpatterns = [
    path('<int:photo_id>/', views.detail, name='detail'),
    re_path(r'^upload/$', views.create, name='create'),
    path('', views.index, name='list'),
    path('delete/', views.delete, name='delete'),

]

pystargram1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import (login as auth_login, logout as auth_logout)
from django.views.generic import TemplateView
from photos import views

urlpatterns = [
    path('', views.index, name='list'),
    path('admin/', admin.site.urls),
    path('photos/', include('photos.urls')),

    path(
        'accounts/login/',
        auth_login,
        name='login',
        kwargs={
            'template_name': 'accounts/login.html'
        }
    ),
    path(
        'accounts/logout/',
        auth_logout,
        name='logout',
        kwargs={
            'next_page': settings.LOGIN_URL
        }
    ),
    re_path(r'^signup/$', views.signup, name='signup'),
    re_path(r'^signup_ok/$', TemplateView.as_view(
        template_name='registration/signup_ok.html'
    ), name='signup_ok'),

]

urlpatterns += static('upload_files', document_root=settings.MEDIA_ROOT)

photos/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User


class Photo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='uploads/%Y/%m/%d/orig')
    filtered_image = models.ImageField(upload_to='uploads/%Y/%m/%d/filtered', blank=True)
    content = models.TextField(max_length=500, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def delete(self, *args, **kwargs):
        self.image.delete()
        self.filtered_image.delete()
        super(Photo, self).delete(*args, **kwargs)


class Question(models.Model):
    """question
    when a user posts questions
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    content = models.TextField()
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated_at']

    def __unicode__(self):
        return u"{0}".format(self.title)

photos/forms.py
from __future__ import unicode_literals

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Photo


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('image', 'content',)


class CreateUserForm(UserCreationForm):
    email = forms.EmailField(required=True) # 이메일 필드 추가

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(CreateUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

photos/views.py
from django.conf import settings
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .models import Photo
from .forms import PhotoForm
from photos.forms import CreateUserForm
from django.contrib import messages

def detail(requset, photo_id):
    photo = get_object_or_404(Photo, pk=photo_id)
    context = dict()
    context['photo'] = photo
    return render(requset, 'photos/detail.html', context)


def create(request):
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)
    if request.method == 'GET':
        form = PhotoForm()
    elif request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)

        if form.is_valid():
            photo = form.save(commit=False)
            photo.user = request.user
            photo.save()
            return redirect('photos:detail', photo_id=photo.pk)

    context = {
        'form': form
    }
    return render(request, 'photos/edit.html', context)


def index(request):
    photos = Photo.objects.all()
    context = dict()
    context['photos'] = photos
    return render(request, 'photos/list.html', context)


def delete(request):
    # 1. POST요청으로온 pk를 받아서 photo모델이 맞는지 찾는다.
    # 2. 틀릴경우 , 다시 해당 페이지/   맞을경우 , photo를 삭제하고 , list 페이지를 보여준다.
    if request.method == 'POST':
        photo_id = request.POST['photo_id']
        try:
            photo = Photo.objects.get(pk=photo_id, user=request.user)
        except :

            return redirect('photos:detail', pk=photo_id)
        photo.delete()
    return redirect('photos:list')


def signup(request):
    if request.method == "POST":
        createuserform = CreateUserForm(request.POST)
        if createuserform.is_valid():
            user = createuserform.save(commit=False)
            user.save()

            return HttpResponseRedirect(reverse("signup_ok"))
    elif request.method == "GET":
        createuserform = CreateUserForm()
    return render(request, "registration/signup.html", {
        "createuserform": createuserform,

    })

templates/accounts/login.html
{% extends 'index.html' %}

{% block content %}
<form method='POST' action="{% url 'login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">로그인</button>
    <br>
<p>아이디가 없으신가요? <a href="{% url 'signup'%}">회원가입</a></p>
</form>
{% endblock %}

templates/base/footer.html
<p>Footer</p>

templates/base/header.html
<nav class="navbar navbar-default">
    <div class="container-fluid"></div>
    <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'list' %}">Photo</a>
    </div>

<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
          {% if request.user.is_authenticated %}
          <li><a href="{% url 'logout' %}">로그아웃</a></li>
          {% else %}
          <li><a href="{% url 'login' %}">로그인</a></li>
          {% endif %}
      </ul>
</div>
</nav>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">

</head>
<body>
{% include 'base/header.html' %}

{% block content %}
{% endblock %}

{% include 'base/footer.html' %}
</body>
</html>

templates/photos/detail.html
{% extends 'index.html' %}

{% block content %}
<div class="container">
        <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
        <h1>{{ photo.pk}}번 사진 보여줄게요</h1>
        <h3>주소는 {{ photo.image.url|truncatechars:40 }}</h3>
        <img src="{{ photo.image.url}}" class="img-thumbnail">

        <form method="POST" action="{% url 'photos:delete' %}">
                {% csrf_token %}
                <input type="hidden" name="photo_id" value="{{ photo.pk }}">
                <button type="submit" class="btn btn-danger btn-lg btn-block">삭제</button>
        </form>
                </div>
                <div class="col-md-2"></div>
        </div>
</div>


{% endblock %}

templates/photos/edit.html
{% extends 'index.html' %}

{% block content %}
<p>{{ request.user.username }}님 환영합니다.</p>
<form
    method="POST"
    action=""
    enctype="multipart/form-data"
>
    {% csrf_token %}
    {{ form.as_p }}

    <p>
        <button type="submit">저장</button>
    </p>
</form>

{% endblock %}

templates/photos/list.html
{% extends 'index.html' %}
{% block content %}
{% if request.user.is_authenticated %}
{% endif %}
<div class="container">
    <div class="row">
        <div>
        <a class="btn btn-default" href="{% url 'photos:create' %}" role="button">사진올리기</a>
        </div>
            {% for photo in photos %}
        <div class="col-md-4">
            <a href="{% url 'photos:detail' photo_id=photo.pk %}">
            <img src="{{ photo.image.url}}" alt="{{ photo.content }}" class="img-thumbnail">
        </div>

        {% endfor %}
    </div>
</div>
{% endblock %}